import {esc,queues,stores,statuses} from './core.js';
const label = s => s.replaceAll('_',' ').replace(/^./, c=>c.toUpperCase());
const options = (values, selected) => values.map(v=>`<option value="${esc(v)}" ${v===selected?'selected':''}>${esc(label(v||'Unassigned'))}</option>`).join('');
const csrf = token => `<input type="hidden" name="csrf" value="${esc(token)}">`;
export function page(title, body, user, token, embedded=false) {
  return `<!doctype html><html lang="en-NZ"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} · Formtech</title><link rel="stylesheet" href="/style.css"></head>
  <body${embedded?' class="embedded"':''}><header><a class="brand" href="${embedded?'/embed':'/'}"><img src="/formtech-logo.png" width="1125" height="182" alt="Formtech"><span>Contact & service</span></a>${embedded?'':`<nav><a href="/">Contact us</a>${user?`<a href="/staff">Enquiries</a><a href="/staff/routing">Phone routing</a>${user.role==='manager'?'<a href="/staff/call-summary">Call summary</a>':''}<form action="/logout" method="post">${csrf(token)}<button class="quiet">Sign out · ${esc(user.username)}</button></form>`:'<a href="/login">Staff sign in</a>'}</nav>`}</header><main>${body}</main><footer>Formtech · Auckland & Christchurch <a href="https://www.formtech.co.nz/" target="_blank" rel="noopener">Visit our store ↗</a></footer>${embedded?'<script src="/embed.js" defer></script>':''}</body></html>`;
}
export function contact(config, token, error='', embedded=false) {
  return page('Contact us', `<div class="eyebrow">LET’S FIND THE RIGHT SOLUTION</div><h1>How can we help?</h1><p class="intro">Talk to our team about your next project, an existing order or getting your machine working again.</p>
  <div class="contact-layout"><aside><div class="card"><h2>One team. Two locations.</h2><p>Auckland · Sales & demonstrations</p><p>Christchurch · Sales & demonstrations</p>${config.publicPhone?`<a class="phone" href="tel:${esc(config.publicPhone)}">${esc(config.publicPhone==='+6498700642'?'09 870 0642':config.publicPhone)}</a>`:'<p>Send an enquiry below and our team will get back to you.</p>'}<hr><p><a href="mailto:orders@formtech.co.nz">orders@formtech.co.nz</a><small>Sales, quotes & orders</small></p><p><a href="mailto:support@formtech.co.nz">support@formtech.co.nz</a><small>Technical support & repairs</small></p><p><a href="mailto:accounts@formtech.co.nz">accounts@formtech.co.nz</a><small>Invoices & payments</small></p></div><p class="muted">For troubleshooting, include your machine model, error message and anything you’ve already tried.</p></aside>
  <form class="card" method="post" action="${embedded?'/embed/enquiries':'/enquiries'}">${csrf(token)}<h2>Send an enquiry</h2>${error?`<p class="notice">${esc(error)}</p>`:''}<div class="grid"><label>Your name<input name="name" required maxlength="120" autocomplete="name"></label><label>Company <span class="muted">(optional)</span><input name="company" maxlength="120" autocomplete="organization"></label><label>Email<input name="email" type="email" maxlength="254" autocomplete="email"></label><label>Phone<input name="phone" type="tel" maxlength="40" autocomplete="tel"></label><label>I need help with<select name="queue">${options(queues,'sales')}</select></label><label>Preferred store<select name="store">${options(stores,'any')}</select></label></div><label>Subject<input name="subject" required maxlength="180"></label><label>Order number / machine model <span class="muted">(optional)</span><input name="product" maxlength="180"></label><label>Tell us a little more<textarea name="message" required maxlength="5000" rows="5"></textarea></label><label class="trap" aria-hidden="true">Leave empty<input name="website" tabindex="-1" autocomplete="off"></label><p class="muted">Provide an email address or phone number so we can reply. Your details will be used to handle this enquiry. <a href="https://www.formtech.co.nz/policies/privacy-policy" target="_blank" rel="noopener">Privacy policy</a></p><button>Send enquiry <span>↗</span></button></form></div>`,null,token,embedded);
}
export function login(token, error='') {
  return page('Staff sign in', `<div class="narrow"><div class="eyebrow">FORMTECH TEAM</div><h1>Welcome back.</h1><form class="card" method="post" action="/login">${csrf(token)}${error?`<p class="notice">${esc(error)}</p>`:''}<label>Username<input name="username" required autocomplete="username" maxlength="40"></label><label>Password<input name="password" type="password" required autocomplete="current-password" maxlength="256"></label><button>Sign in</button></form></div>`);
}
export function dashboard(items,user,token,filter) {
  const active = items.filter(i=>i.status!=='resolved');
  const rows=items.filter(i=>(!filter.queue||i.queue===filter.queue)&&(!filter.status||i.status===filter.status)&&(!filter.store||i.store===filter.store)&&(!filter.q||`${i.reference} ${i.name} ${i.email} ${i.subject} ${i.phone}`.toLowerCase().includes(filter.q.toLowerCase())));
  return page('Enquiries',`<div class="eyebrow">TEAM WORKSPACE</div><h1>Every enquiry, accounted for.</h1><p class="intro">Assign the next step. Keep the customer moving.</p><div class="metrics">${[['Open enquiries',active.length],['Callbacks due',active.filter(i=>i.callback).length],['Overdue',active.filter(i=>i.due_at&&i.due_at<new Date().toISOString().slice(0,10)).length],['Sales enquiries',items.filter(i=>i.queue==='sales').length]].map(([name,n])=>`<div class="card"><strong>${n}</strong><span>${name}</span></div>`).join('')}</div>
  <form class="filters" method="get"><label>Search<input name="q" value="${esc(filter.q||'')}" placeholder="Name, reference, phone…"></label><label>Queue<select name="queue"><option value="">All queues</option>${options(user.role==='accounts'?['accounts']:user.role==='agent'?queues.filter(q=>q!=='accounts'):queues,filter.queue)}</select></label><label>Store<select name="store"><option value="">All stores</option>${options(stores,filter.store)}</select></label><label>Status<select name="status"><option value="">All statuses</option>${options(statuses,filter.status)}</select></label><button>Filter</button></form>
  <div class="card table-wrap"><table><thead><tr><th>Enquiry</th><th>Queue / store</th><th>Owner</th><th>Status</th><th>Received</th></tr></thead><tbody>${rows.map(i=>`<tr><td><a href="/staff/enquiries/${i.id}"><b>${esc(i.subject)}</b></a><small>${esc(i.reference)} · ${esc(i.name||i.phone||i.email||'Caller')} · ${esc(i.channel)}</small></td><td>${esc(label(i.queue))}<small>${esc(label(i.store))}</small></td><td>${esc(i.owner||'Unassigned')}</td><td><span class="badge">${esc(label(i.status))}</span>${i.callback&&i.status!=='resolved'?'<small class="callback">Callback needed</small>':''}</td><td>${esc(i.created_at.slice(0,10))}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No enquiries here yet.</td></tr>'}</tbody></table></div><p class="muted">Counts reflect the queues you can access. Filters apply to the table. Dates are shown in UTC.</p>`,user,token);
}
export function detail(i,notes,users,user,token,config) {
  const support = i.queue==='support' ? `<div class="notice"><b>Support is managed in HubSpot.</b> ${i.hubspot_ticket_id && /^\d+$/.test(config.hubspot.portal) ? `<a href="https://app.hubspot.com/contacts/${esc(config.hubspot.portal)}/record/0-5/${esc(i.hubspot_ticket_id)}">Open ticket ${esc(i.hubspot_ticket_id)} ↗</a>` : i.hubspot_ticket_id ? `Ticket ${esc(i.hubspot_ticket_id)} created.` : esc(i.hubspot_error||'Awaiting HubSpot handoff. Integration credentials must be configured.')}<p>Local status and notes track call follow-up only. Manage support ownership, replies and resolution in HubSpot.</p></div>` : '';
  return page(i.reference,`<a class="back" href="/staff">← All enquiries</a><div class="eyebrow">${esc(i.reference)} · ${esc(i.channel)}</div><h1>${esc(i.subject)}</h1>${support}<div class="contact-layout"><aside class="card"><h2>Customer details</h2><p>${esc(i.name||'Caller')}</p><p>${esc(i.email)}</p><p>${esc(i.phone)}</p><p>${esc(label(i.queue))} · ${esc(label(i.store))}</p><hr><p class="pre">${esc(i.message)}</p>${i.channel==='phone'?`<hr><p>Call status: ${esc(i.call_status||'Incoming')}</p><p>Staff accepted: ${i.accepted?'Yes':'No'}</p><p>Voicemail: ${esc(i.recording_sid||'None received')}</p><small>Listen to voicemail in the authenticated Twilio console using this recording ID.</small>`:''}</aside><section><form class="card" method="post" action="/staff/enquiries/${i.id}">${csrf(token)}<h2>Next steps</h2><div class="grid"><label>Owner<select name="owner">${options(['',...users.filter(u=>u.role==='manager'||(i.queue==='accounts'?u.role==='accounts':u.role==='agent')).map(u=>u.username)],i.owner)}</select></label><label>Status<select name="status">${options(statuses,i.status)}</select></label><label>Due date<input name="due_at" type="date" value="${esc(i.due_at)}"></label><label>Sales outcome<select name="outcome">${options(['','qualified','quoted','won','lost'],i.outcome)}</select></label><label>Quote value (NZD)<input type="number" name="quote_value" min="0" max="100000000" step="0.01" value="${i.quote_value??''}"></label><label>Callback<select name="callback">${options(['needed','complete'],i.callback?'needed':'complete')}</select></label></div><label>Next action<input name="next_action" maxlength="500" value="${esc(i.next_action)}"></label><label>Add an internal note<textarea name="note" rows="3" maxlength="5000"></textarea></label><button>Save changes</button></form><h2>Activity</h2>${notes.map(n=>`<article class="card note"><b>${esc(n.author)}</b><small>${esc(n.created_at)}</small><p class="pre">${esc(n.body)}</p></article>`).join('')||'<p class="muted">No staff updates yet.</p>'}</section></div>`,user,token);
}
export function routing(config,user,token) {
  return page('Phone routing',`<div class="eyebrow">PHONE SERVICE</div><h1>The right person, first.</h1><p class="notice">${config.enabled?'Phone forwarding enabled in configuration. Verify the provider number is connected.':'Phone forwarding is disabled. Configure and test your provider before going live.'}</p><div class="card table-wrap"><table><thead><tr><th>Press</th><th>Enquiry</th><th>Store</th><th>Primary</th><th>Backup</th></tr></thead><tbody>${Object.entries(config.routes).map(([key,r])=>`<tr><td>${key}</td><td>${esc(r.label)}</td><td>${esc(label(r.store))}</td><td>${r.phone?'Configured':'Voicemail only'}</td><td>${r.backup?'Configured':'None'}</td></tr>`).join('')}</tbody></table></div><p>After hours, unanswered calls and callers who make no selection are offered voicemail. Staff must press 1 before a caller is connected.</p><p class="muted">Destinations and hours are managed through deployment configuration. Personal mobile numbers are never shown on the public contact page.</p>`,user,token);
}
